all: word_search

word_search: Puzzle.o functions.o Puzzle.h
	gcc Puzzle.o functions.o Puzzle.h -o word_search

Puzzle.o: Puzzle.c
	gcc -c Puzzle.c
	
functions.o: functions.c
	gcc -c functions.c
	
clean :
	rm -rf *.o word_search;
